# IN-CODE CITATION:
# Contributed by ChatGPT 5.2 (OpenAI) in February, 2026.
# Level of contribution: (3) AI-Drafted Implementation 
# The full implementation was initially generated by ChatGPT and subsequently 
# reviewed, edited, optimized, or refactored manually.
# Prompt used:
# """Write a minimal Python module that implements a thread-safe 
# in-memory session store for storing message histories. Messages are
# implemented as MessageHistory objects, imported from
# domain_qa.core.llm.message_history.
# """

from __future__ import annotations

from dataclasses import dataclass
from threading import RLock
from typing import Dict, Protocol

from domain_qa.core.llm.message_history import MessageHistory


class SessionStore(Protocol):
    def get(self, session_id: str) -> MessageHistory: ...
    def save(self, session_id: str, history: MessageHistory) -> None: ...


@dataclass
class InMemorySessionStore(SessionStore):
    _lock: RLock = RLock()
    _data: Dict[str, MessageHistory] = None  # type: ignore

    def __post_init__(self) -> None:
        if self._data is None:
            self._data = {}

    def get(self, session_id: str) -> MessageHistory:
        with self._lock:
            return self._data.get(session_id, MessageHistory())

    def save(self, session_id: str, history: MessageHistory) -> None:
        with self._lock:
            self._data[session_id] = history