# IN-CODE CITATION:
# Generated by ChatGPT 5.2 (OpenAI) on FEb 27, 2026.
# Prompt used:
# """Write a minimal Python module that implements a thread-safe 
# in-memory session store for storing message histories. Messages are
# implemented as MessageHistory objects, imported from
# domain_qa.core.llm.message_history.
# """
# Code has been manually verified and slightly modified.

from __future__ import annotations

from dataclasses import dataclass
from threading import RLock
from typing import Dict, Protocol

from domain_qa.core.llm.message_history import MessageHistory


class SessionStore(Protocol):
    def get(self, session_id: str) -> MessageHistory: ...
    def save(self, session_id: str, history: MessageHistory) -> None: ...


@dataclass
class InMemorySessionStore(SessionStore):
    _lock: RLock = RLock()
    _data: Dict[str, MessageHistory] = None  # type: ignore

    def __post_init__(self) -> None:
        if self._data is None:
            self._data = {}

    def get(self, session_id: str) -> MessageHistory:
        with self._lock:
            return self._data.get(session_id, MessageHistory())

    def save(self, session_id: str, history: MessageHistory) -> None:
        with self._lock:
            self._data[session_id] = history